### ISSUE TITLE
New version does not show zone names

### ISSUE THREAD

**Issue by jlrosssc** [dahlb/ha_carrier#194]
### System Health details

N/A

### Checklist

- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [x] This issue is not a duplicate issue of currently [previous issues](https://github.com/dahlb/ha_carrier/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

New version has lost zone names and only shoes Zone 1, Zone 2, etc. 

### Reproduction steps

1.NA
2.
3.
...

### Debug logs

```text
NA
```

**Comment by dahlb** [comment]
should be fixed in 2.1.8

**Comment by LSR19** [comment]
> should be fixed in 2.1.8
Was this bug fixed in released 2.1.8 (the issue is still listed here as Open).

**Comment by jlrosssc** [comment]
If corrected mine when I updated. Sent from my iPhoneOn Feb 19, 2025, at 10:30 AM, LSR19 ***@***.***> wrote:﻿
  
should be fixed in 2.1.8
Was this bug fixed in released 2.1.8 (the issue is still listed here as Open).
—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>



LSR19 left a comment (dahlb/ha_carrier#194)

should be fixed in 2.1.8
Was this bug fixed in released 2.1.8 (the issue is still listed here as Open).
